kind: Service
apiVersion: v1
metadata: 
  name: addressapiservice
  labels:
    app: addressapiservice
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: addressapi   
  type: NodePort