kind: Service
apiVersion: v1
metadata: 
  name: testocenewmsservice
  labels:
    app: testocenewmsservice
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: testocenewms   
  type: NodePort